wobe_imports/__manifest__.py, wobe_imports/models/ftp.py, wobe_imports/models/wobe.py, wobe_imports/security/ir.model.access.csv, wobe_imports/views/ftp_view.xml, wobe_imports/views/wobe_view.xml
Had Push challenges, thus new branch was created.
=> Dev deepa latest

wobe_imports/data/cron_data.xml, wobe_imports/models/ftp.py, wobe_imports/models/wobe.py, wobe_imports/views/wobe_view.xml
=> Wobe: PartialFile reading

wobe_imports/models/wobe.py
=> Wobe: UpdateFromDuplicateRecords

wobe_imports/models/ftp.py, wobe_imports/models/wobe.py
=> Wobe: DuplicateRecord-Enhances

wobe_imports/models/wobe.py, wobe_imports/views/wobe_view.xml
=> make wobe_jobs_form_view editable for XML1

wobe_imports/models/wobe.py, wobe_imports/security/ir.model.access.csv, wobe_imports/views/wobe_view.xml
=> Wobe: Button 'Convert to Regioman'

wobe_imports/__manifest__.py, wobe_imports/data/product_data.xml, wobe_imports/models/__init__.py, wobe_imports/models/sale_order.py, wobe_imports/models/stock.py, wobe_imports/models/wobe.py, wobe_imports/views/stock_view.xml, wobe_imports/views/wobe_view.xml
=> Dev deepa latest7

wobe_imports/models/wobe.py, wobe_imports/views/wobe_view.xml
=> Wobe: Paper-Roll enhances

bdu_crm/__manifest__.py, bdu_crm/models/__init__.py, bdu_crm/models/project.py, bdu_crm/security/ir.model.access.csv, bdu_crm/views/project_view.xml
Task : https://bo-test.bdu.nl/web#id=34&view_type=form&model=project.task&menu_id=93&action=142
Module: bdu_crm
=> Add fields to project.task

bdu_account/__init__.py, bdu_account/__manifest__.py, bdu_account/report/report.xml, bdu_account/report/report_credit_control_summary.xml, bdu_account/report/report_invoice.xml, bdu_account/report/report_saleorder.xml, bdu_account/views/res_partner_view.xml, bdu_account/wizard/__init__.py, bdu_account/wizard/credit_control_communication.py, bdu_pubble_soap/i18n/nl.po, bdu_pubble_soap/models/sale_advertising.py, bdu_pubble_soap/views/sale_advertising_order.xml, wobe_imports/models/ftp.py, wobe_imports/models/wobe.py
Tasks: https://bo-test.bdu.nl/web#id=44&view_type=form&model=project.task&action=142
Module: wobe_imports.
=> Wobe issue fixed

bdu_account/report/report_invoice.xml, bdu_account/report/report_saleorder.xml
Add filter for is_ad_agency in report.
Module: bdu_account
=> Report BDUmedia quotation & invoice layout

bdu_pubble_soap/models/sale_advertising.py, wobe_imports/__manifest__.py, wobe_imports/models/analytic.py, wobe_imports/models/stock.py, wobe_imports/views/analytic_view.xml, wobe_imports/views/stock_view.xml, wobe_imports/views/wobe_view.xml
Task: New fields in stock.move and analytic.line tree
Module: wobe_imports
=> Task: New fields in stock.move and analytic.line tree

bdu_account/__manifest__.py, bdu_account/models/account_invoice.py, bdu_account/report/report_invoice.xml, bdu_account/report/report_saleorder.xml, nl.po, wobe_imports/models/ftp.py, wobe_imports/models/wobe.py, wobe_imports/views/ftp_view.xml, wobe_imports/views/wobe_view.xml
Task: FTP multi path.
Module: wobe_imports
=> Wobe Interface: Muti server path

bdu_account/__manifest__.py, bdu_account/models/res_partner.py, bdu_account/models/sale.py, bdu_account/report/report_invoice.xml, bdu_account/report/report_saleorder.xml, bdu_account/views/res_partner_view.xml, bdu_account/views/sale_advertising_view.xml, disable_follower_mails/__init__.py, disable_follower_mails/__manifest__.py, disable_follower_mails/models/__init__.py, disable_follower_mails/models/mail_followers_config.py, disable_follower_mails/models/mail_message.py, disable_follower_mails/security/ir.model.access.csv, disable_follower_mails/views/mail_followers_config_view.xml, disable_follower_mails/wizard/__init__.py, disable_follower_mails/wizard/mail_wizard_invite.py
Tasks: GEN-1 Rule for messages to external followers
link: https://bo-test.bdu.nl/web#id=107&view_type=form&model=project.task&menu_id=93&action=142
Module: Disable_follower_mails
=> Disable mail notification to followers with domain.

bdu_account/__manifest__.py, bdu_account/report/report_credit_control_summary.xml
Credit control report enhancement.
Module: bdu_account
=> bdu_account

bdu_crm/models/project.py, bdu_crm/models/project_issue.py, bdu_crm/security/ir.model.access.csv, bdu_crm/views/project_issue_view.xml
Module: bdu_crm
PRO-1 Remove restriction of maximum choices from issue_type field in project.issue
Link: https://bo-test.bdu.nl/web#id=119&view_type=form&model=project.task&menu_id=103&action=142
PRO-2 Make it possible to link a project issue type to a project
Link : https://bo-test.bdu.nl/web#id=120&view_type=form&model=project.task&menu_id=103&action=142
PRO-3 project.solution configuration / access control
Link: https://bo-test.bdu.nl/web#id=121&view_type=form&model=project.task&menu_id=103&action=142
=> PRO-1, PRO-2, PRO-3

bdu_announcements/__manifest__.py, bdu_announcements/security/ir.model.access.csv, bdu_announcements/security/security.xml, bdu_reports/__init__.py, bdu_reports/__manifest__.py, bdu_reports/models/__init__.py, bdu_reports/models/account_invoice.py, bdu_reports/models/credit_history.py, bdu_reports/reports/qa_reports.xml, bdu_reports/security/ir.model.access.csv, bdu_reports/security/security.xml, bdu_reports/views/credit_history.xml
=> security added

bdu_product_online/models/profile.py, bdu_product_online/security/security.xml
security issues repaired because starting conditions where different on O than on T
=> BDU Jam nav test

bdu_peacock/models/peacock_config.py, bdu_product_distribution/__manifest__.py, bdu_product_distribution/reports/reports.xml, bdu_product_online/models/profile.py, bdu_product_online/views/orderline_adaptions.xml, bdu_product_online/views/profile.xml, bdu_pubble_reverse_billing/__manifest__.py, bdu_pubble_reverse_billing/models/pubble_production_data.py, bdu_pubble_reverse_billing/security/security.xml, bdu_pubble_reverse_billing/views/pubble_reverse_billing_info.xml
=> BDU Pubble reverse billing

bdu_pubble_reverse_billing/models/pubble_production_data.py
@whulshof : wil je deze naar test zetten? Er wordt nu eindelijk een beetje getest met reverse billing en ik houd er graag de gang in.
=> BDU pubble reverse billing : remove debug +  search-> filtered/mapped

bdu_delivery/models/delivery_config.py, bdu_wave2/models/wave2_config.py
additionally logging added so timestamps may reveal source of time consumption
=> bdu_delivery : performance update

bdu_delivery/models/delivery_config.py, bdu_product_recruitment/models/sale.py, bdu_product_recruitment/views/orderline_adaptions.xml, bdu_recruitment_online/models/recruitment_config.py, bdu_sale_advertising/models/bdu_sale_advertising.py
needs a change in sale_advertising_orders as well
=> bdu_sale_advertising : refactoring of automated invoices

disable_follower_mails/models/__init__.py, disable_follower_mails/models/mail_followers_config.py, disable_follower_mails/models/mail_message.py, disable_follower_mails/models/mail_thread.py, disable_follower_mails/models/res_partner.py, disable_follower_mails/views/mail_followers_config_view.xml
Task:T0239 - disable automatic mails to followers
Module:disable_follower_mails
=> Task:T0239 - disable automatic mails to followers

bdu_account/__manifest__.py, bdu_account/i18n/nl.po, bdu_account/models/res_partner.py, bdu_announcements/models/announcement_config.py, bdu_paid_digital_subscriptions/models/digital_subscribers_config.py, bdu_sale_advertising/models/bdu_sale_advertising.py, bdu_wave2/models/wave2_config.py, bdu_wave2/models/wave2_order.py, bdu_wave2/views/wave2_config.xml, bdu_wave2/views/wave2_order.xml
wave2 : move done orders to other dir, default values for orders and new web partners, zip check and zip sanitise, link to order, ...
bdu_paid_digital_subscriptions : FTPS instead of FTP
bdu_announcement and bdu_sale_advertising : job decorators added
=> several bdu_addons : see comment

wobe_imports/models/wobe.py
FIX: environment variable causing job roll updates on edition roll update
Module:wobe_imports
=>  FIX: environment variable causing job roll updates on edition roll update

bdu_wave2/models/wave2_config.py
plus some coding standards (single space) instead of aligned equal signs
=> bdu_wave2 : res.users instead of res.partner for account manager
